name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Create .env file
      run: |
        touch .env
        echo qiwi_secret_key=${{ secrets.QIWI_SECRET_KEY }} >> .env
        echo yoomoney_access_token=${{ secrets.YOOMONEY_ACCESS_TOKEN }} >> .env
        echo payok_api_key=${{ secrets.PAYOK_API_KEY }} >> .env
        echo payok_api_id=${{ secrets.PAYOK_API_ID }} >> .env
        echo payok_shop_id=${{ secrets.PAYOK_SHOP_ID }} >> .env
        echo payok_shop_secret_key=${{ secrets.PAYOK_SHOP_SECRET_KEY }} >> .env
        echo lava_token=${{ secrets.LAVA_TOKEN }} >> .env
        echo lava_wallet=${{ secrets.LAVA_WALLET }} >> .env
        cat .env
    - name: Test with tox
      run: tox
